# Generated by Django 5.0.7 on 2025-08-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "map_svg",
                    models.FileField(
                        blank=True,
                        help_text="SVG file for the floor plan visual",
                        null=True,
                        upload_to="floor_plans/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Unique desk identifier (e.g., '1.L.12')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("permanent", "Permanently Assigned"),
                            ("disabled", "Disabled"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "pos_x",
                    models.IntegerField(
                        blank=True, help_text="X-coordinate for map view", null=True
                    ),
                ),
                (
                    "pos_y",
                    models.IntegerField(
                        blank=True, help_text="Y-coordinate for map view", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="core.area",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
    ]
